[package]
name = "qiara_token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "qiara_token"

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = "0.31.1"
qiara = { path = "../qiara", features = ["cpi"] }

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
idl-build = [
    "anchor-lang/idl-build",
    "anchor-spl/idl-build",
    "qiara/idl-build",
]