use anchor_lang::prelude::*;
use anchor_lang::solana_program::keccak;
use anchor_lang::solana_program::secp256k1_recover::secp256k1_recover;
use anchor_spl::token::{self, Burn, Mint, MintTo, Token, TokenAccount, Transfer};

declare_id!("b8FfSsqju7xF2D9U1Ue7wBsfq3xMLP234HaFqiDomUL");

pub const FEE_DENOMINATOR: u128 = 100_000_000; // 1_000_000 = 1% | 250 = 0.00025%

// Alt-BN128 native syscall ops
const ALT_BN128_ADD: u64 = 0;
const ALT_BN128_MUL: u64 = 2;
const ALT_BN128_PAIRING: u64 = 3;

extern "C" {
    fn sol_alt_bn128_group_op(
        group_op: u64,
        input: *const u8,
        input_size: u64,
        result: *mut u8,
    ) -> u64;
}

// =========================================================================
// GROTH16 ALT-BN128 VERIFYING KEY (Generated by export-rust-vk.js)
// =========================================================================

pub const QIARA_ALPHA_G1: [u8; 64] = [0x00; 64];
pub const QIARA_BETA_NEG_G2: [u8; 128] = [0x00; 128];
pub const QIARA_GAMMA_NEG_G2: [u8; 128] = [0x00; 128];
pub const QIARA_DELTA_NEG_G2: [u8; 128] = [0x00; 128];

pub const QIARA_IC_POINTS: &[[u8; 64]] = &[
    [0x00; 64], // CONSTANT
    [0x00; 64], // PUB_0: OldAccountRoot
    [0x00; 64], // PUB_1: NewAccountRoot
    [0x00; 64], // PUB_2: UserAddress
    [0x00; 64], // PUB_3: PackedTxData
];

#[program]
pub mod qiara_token {
    use super::*;

    /// Initialize Qiara Token with 1,000,000 initial supply (9 decimals)
    pub fn initialize(ctx: Context<Initialize>, variable_header: String) -> Result<()> {
        let config = &mut ctx.accounts.config;
        config.authority = ctx.accounts.authority.key();
        config.mint = ctx.accounts.mint.key();
        config.mint_bump = ctx.bumps.mint_authority;
        config.variable_header = if variable_header.is_empty() {
            "QiaraToken".to_string()
        } else {
            variable_header
        };
        config.fee_recipient = None;

        let seeds = &[b"mint-authority".as_ref(), &[config.mint_bump]];
        token::mint_to(
            CpiContext::new_with_signer(
                ctx.accounts.token_program.to_account_info(),
                MintTo {
                    mint: ctx.accounts.mint.to_account_info(),
                    to: ctx.accounts.admin_token_account.to_account_info(),
                    authority: ctx.accounts.mint_authority.to_account_info(),
                },
                &[&seeds[..]],
            ),
            1_000_000 * 1_000_000_000,
        )?;

        Ok(())
    }

    /// ZK Mint: In-program Groth16 verification + validator quorum without CPI overhead
    pub fn zk_mint(
        ctx: Context<ZkMint>,
        nullifier: [u8; 32],
        public_inputs: Vec<u8>,
        proof_points: Vec<u8>,
        signatures: Vec<Vec<u8>>,
    ) -> Result<()> {
        require!(public_inputs.len() == 128, QiaraTokenError::InvalidInputLength);

        // 1. Validator Quorum Check
        verify_signatures(
            &ctx.accounts.validator_state,
            &ctx.accounts.registry,
            &signatures,
            &public_inputs,
        )?;

        // 2. Direct Alt-BN128 Groth16 Proof Verification (No CPI)
        let is_valid = verify_groth16_proof(&public_inputs, &proof_points)?;
        require!(is_valid, QiaraTokenError::InvalidProof);

        // 3. Mark Nullifier as Used
        ctx.accounts.nullifier_record.is_used = true;

        // 4. Unpack Signals: Recipient(64..96), PackedTxData(96..128)
        let expected_user = Pubkey::new_from_array(public_inputs[64..96].try_into().unwrap());
        require!(ctx.accounts.recipient.key() == expected_user, QiaraTokenError::UnauthorizedRecipient);

        let packed_bytes = &public_inputs[96..128];
        let amount = u64::from_le_bytes(packed_bytes[0..8].try_into().unwrap());

        // 5. Mint tokens via PDA
        let seeds = &[b"mint-authority".as_ref(), &[ctx.accounts.config.mint_bump]];
        token::mint_to(
            CpiContext::new_with_signer(
                ctx.accounts.token_program.to_account_info(),
                MintTo {
                    mint: ctx.accounts.mint.to_account_info(),
                    to: ctx.accounts.recipient_token_account.to_account_info(),
                    authority: ctx.accounts.mint_authority.to_account_info(),
                },
                &[&seeds[..]],
            ),
            amount,
        )?;

        emit!(ZkMintEvent {
            recipient: expected_user,
            amount,
            nullifier,
        });

        Ok(())
    }

    /// Transfer with dynamic epoch burn fee
    pub fn transfer_with_fee(ctx: Context<TransferWithFee>, amount: u64) -> Result<()> {
        let is_sender_exempt = ctx.accounts.sender_exempt.is_some();
        let is_recipient_exempt = ctx.accounts.recipient_exempt.is_some();

        let fee = if is_sender_exempt || is_recipient_exempt {
            0
        } else {
            calculate_transfer_fee(
                &ctx.accounts.registry,
                &ctx.accounts.epoch_config,
                &ctx.accounts.config.variable_header,
                amount,
            )?
        };

        let transfer_amount = amount.checked_sub(fee).ok_or(QiaraTokenError::FeeExceedsAmount)?;

        // 1. Transfer net tokens
        token::transfer(
            CpiContext::new(
                ctx.accounts.token_program.to_account_info(),
                Transfer {
                    from: ctx.accounts.from.to_account_info(),
                    to: ctx.accounts.to.to_account_info(),
                    authority: ctx.accounts.authority.to_account_info(),
                },
            ),
            transfer_amount,
        )?;

        // 2. Burn fee or send to fee recipient
        if fee > 0 {
            if let Some(fee_ata) = &ctx.accounts.fee_recipient_ata {
                token::transfer(
                    CpiContext::new(
                        ctx.accounts.token_program.to_account_info(),
                        Transfer {
                            from: ctx.accounts.from.to_account_info(),
                            to: fee_ata.to_account_info(),
                            authority: ctx.accounts.authority.to_account_info(),
                        },
                    ),
                    fee,
                )?;
            } else {
                token::burn(
                    CpiContext::new(
                        ctx.accounts.token_program.to_account_info(),
                        Burn {
                            mint: ctx.accounts.mint.to_account_info(),
                            from: ctx.accounts.from.to_account_info(),
                            authority: ctx.accounts.authority.to_account_info(),
                        },
                    ),
                    fee,
                )?;
            }
        }

        Ok(())
    }

    /// Update fee exemption status
    pub fn set_fee_exempt(ctx: Context<SetFeeExempt>, exempt: bool) -> Result<()> {
        let admin_bytes = ctx
            .accounts
            .registry
            .get_active_variable(&ctx.accounts.config.variable_header, "WHITELIST_ADMIN");

        let authorized_admin = admin_bytes
            .and_then(|b| if b.len() == 32 { Some(Pubkey::new_from_array(b.try_into().unwrap())) } else { None })
            .unwrap_or(ctx.accounts.config.authority);

        require!(
            ctx.accounts.signer.key() == authorized_admin || ctx.accounts.signer.key() == ctx.accounts.config.authority,
            QiaraTokenError::UnauthorizedWhitelistAdmin
        );

        ctx.accounts.exempt_record.account = ctx.accounts.target_wallet.key();
        ctx.accounts.exempt_record.is_exempt = exempt;
        Ok(())
    }
}

// =========================================================================
// GROTH16 & CRYPTO VERIFICATION CORE
// =========================================================================

pub fn verify_groth16_proof(public_inputs: &[u8], proof_points: &[u8]) -> Result<bool> {
    if proof_points.len() < 256 || public_inputs.len() < 128 {
        return err!(QiaraTokenError::InvalidProof);
    }

    let proof_a = &proof_points[0..64];
    let proof_b = &proof_points[64..192];
    let proof_c = &proof_points[192..256];

    // 1. Multi-Scalar Multiplication (MSM)
    let mut prepared_inputs = [0u8; 64];
    prepared_inputs.copy_from_slice(&QIARA_IC_POINTS[0]);

    for (i, chunk) in public_inputs.chunks_exact(32).enumerate() {
        if i + 1 >= QIARA_IC_POINTS.len() {
            break;
        }

        let ic_point = &QIARA_IC_POINTS[i + 1];
        if ic_point.iter().all(|&b| b == 0) {
            continue;
        }

        let mut mul_input = [0u8; 96];
        mul_input[0..64].copy_from_slice(ic_point);
        mul_input[64..96].copy_from_slice(chunk);

        let mut mul_output = [0u8; 64];
        let res = unsafe {
            sol_alt_bn128_group_op(
                ALT_BN128_MUL,
                mul_input.as_ptr(),
                96,
                mul_output.as_mut_ptr(),
            )
        };
        if res != 0 {
            return err!(QiaraTokenError::InvalidProof);
        }

        let mut add_input = [0u8; 128];
        add_input[0..64].copy_from_slice(&prepared_inputs);
        add_input[64..128].copy_from_slice(&mul_output);

        let mut add_output = [0u8; 64];
        let res = unsafe {
            sol_alt_bn128_group_op(
                ALT_BN128_ADD,
                add_input.as_ptr(),
                128,
                add_output.as_mut_ptr(),
            )
        };
        if res != 0 {
            return err!(QiaraTokenError::InvalidProof);
        }

        prepared_inputs = add_output;
    }

    // 2. Alt-BN128 4-Pairing Check
    let mut pairing_input = [0u8; 768];
    pairing_input[0..64].copy_from_slice(proof_a);
    pairing_input[64..192].copy_from_slice(proof_b);
    pairing_input[192..256].copy_from_slice(proof_c);
    pairing_input[256..384].copy_from_slice(&QIARA_DELTA_NEG_G2);
    pairing_input[384..448].copy_from_slice(&QIARA_ALPHA_G1);
    pairing_input[448..576].copy_from_slice(&QIARA_BETA_NEG_G2);
    pairing_input[576..640].copy_from_slice(&prepared_inputs);
    pairing_input[640..768].copy_from_slice(&QIARA_GAMMA_NEG_G2);

    let mut pairing_result = [0u8; 32];
    let res = unsafe {
        sol_alt_bn128_group_op(
            ALT_BN128_PAIRING,
            pairing_input.as_ptr(),
            768,
            pairing_result.as_mut_ptr(),
        )
    };

    if res != 0 || pairing_result[31] != 1 {
        return err!(QiaraTokenError::InvalidProof);
    }

    Ok(true)
}

fn verify_signatures(
    state: &qiara::ValidatorState,
    registry: &qiara::Registry,
    signatures: &[Vec<u8>],
    inputs: &[u8],
) -> Result<()> {
    let min_required = registry.get_min_unique_validators();
    require!(signatures.len() >= min_required, QiaraTokenError::InsufficientSignatures);

    let mut data = Vec::with_capacity(inputs.len());
    for chunk in inputs.chunks_exact(32) {
        let mut chunk_rev = [0u8; 32];
        chunk_rev.copy_from_slice(chunk);
        chunk_rev.reverse();
        data.extend_from_slice(&chunk_rev);
    }
    let msg_hash = keccak::hash(&data).to_bytes();

    let mut seen_signers: Vec<Vec<u8>> = Vec::with_capacity(signatures.len());

    for sig in signatures {
        if sig.len() != 65 {
            continue;
        }

        let mut sig_bytes = [0u8; 64];
        sig_bytes.copy_from_slice(&sig[0..64]);
        let recovery_id = sig[64];

        if let Ok(recovered_raw) = secp256k1_recover(&msg_hash, recovery_id, &sig_bytes) {
            let mut recovered_uncompressed = Vec::with_capacity(65);
            recovered_uncompressed.push(0x04);
            recovered_uncompressed.extend_from_slice(&recovered_raw.to_bytes());

            if state.active_pubkeys.contains(&recovered_uncompressed)
                && !seen_signers.contains(&recovered_uncompressed)
            {
                seen_signers.push(recovered_uncompressed);
            }
        }
    }

    require!(seen_signers.len() >= min_required, QiaraTokenError::InsufficientSignatures);
    Ok(())
}

// =========================================================================
// FEE CALCULATION
// =========================================================================

pub fn calculate_transfer_fee(
    registry: &qiara::Registry,
    epoch_config: &qiara::EpochConfig,
    header: &str,
    amount: u64,
) -> Result<u64> {
    let base_rate = read_u64(registry, header, "BURN_FEE").unwrap_or(0);
    if base_rate == 0 {
        return Ok(0);
    }

    let increase = read_u64(registry, header, "BURN_INCREASE").unwrap_or(0);
    let epoch = epoch_config.get_current_epoch()?;
    let mut rate = (base_rate as u128) + ((increase as u128) * (epoch as u128));

    if let Some(max_rate) = read_u64(registry, header, "BURN_FEE_MAXIMAL") {
        if max_rate > 0 && rate > (max_rate as u128) {
            rate = max_rate as u128;
        }
    }
    if rate > FEE_DENOMINATOR {
        rate = FEE_DENOMINATOR;
    }

    let mut fee = (((amount as u128) * rate) / FEE_DENOMINATOR) as u64;

    if let Some(raw_min) = read_u64(registry, header, "BURN_FEE_MINIMAL") {
        let min_fee = if raw_min >= 100_000 { raw_min } else { raw_min * 1000 };
        if fee < min_fee {
            fee = min_fee;
        }
    }

    Ok(if fee > amount { amount } else { fee })
}

fn read_u64(registry: &qiara::Registry, header: &str, name: &str) -> Option<u64> {
    let bytes = registry.get_active_variable(header, name)?;
    if bytes.len() == 8 {
        Some(u64::from_be_bytes(bytes.try_into().unwrap()))
    } else {
        None
    }
}

// =========================================================================
// ACCOUNTS & CONTEXTS
// =========================================================================

#[account]
pub struct Config {
    pub authority: Pubkey,
    pub mint: Pubkey,
    pub mint_bump: u8,
    pub variable_header: String,
    pub fee_recipient: Option<Pubkey>,
}

#[account]
pub struct NullifierRecord {
    pub is_used: bool,
}

#[account]
pub struct ExemptRecord {
    pub account: Pubkey,
    pub is_exempt: bool,
}

#[derive(Accounts)]
#[instruction(variable_header: String)]
pub struct Initialize<'info> {
    #[account(
        init,
        payer = authority,
        space = 8 + 32 + 32 + 1 + (4 + variable_header.len()) + 33,
        seeds = [b"config"],
        bump
    )]
    pub config: Account<'info, Config>,

    #[account(
        init,
        payer = authority,
        mint::decimals = 9,
        mint::authority = mint_authority,
    )]
    pub mint: Account<'info, Mint>,

    /// CHECK: PDA mint authority
    #[account(seeds = [b"mint-authority"], bump)]
    pub mint_authority: AccountInfo<'info>,

    #[account(mut)]
    pub admin_token_account: Account<'info, TokenAccount>,

    #[account(mut)]
    pub authority: Signer<'info>,
    pub system_program: Program<'info, System>,
    pub token_program: Program<'info, Token>,
}

#[derive(Accounts)]
#[instruction(nullifier: [u8; 32])]
pub struct ZkMint<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,

    /// CHECK: Recipient user matching public signal
    pub recipient: AccountInfo<'info>,

    #[account(mut)]
    pub config: Account<'info, Config>,

    #[account(mut, address = config.mint)]
    pub mint: Account<'info, Mint>,

    /// CHECK: PDA mint authority
    #[account(seeds = [b"mint-authority"], bump = config.mint_bump)]
    pub mint_authority: AccountInfo<'info>,

    #[account(mut)]
    pub recipient_token_account: Account<'info, TokenAccount>,

    #[account(
        init,
        payer = payer,
        space = 8 + 1,
        seeds = [b"nullifier", nullifier.as_ref()],
        bump
    )]
    pub nullifier_record: Account<'info, NullifierRecord>,

    // Verification accounts
    pub registry: Account<'info, qiara::Registry>,
    pub validator_state: Account<'info, qiara::ValidatorState>,

    pub system_program: Program<'info, System>,
    pub token_program: Program<'info, Token>,
}

#[derive(Accounts)]
pub struct TransferWithFee<'info> {
    #[account(mut)]
    pub from: Account<'info, TokenAccount>,
    #[account(mut)]
    pub to: Account<'info, TokenAccount>,
    #[account(mut)]
    pub mint: Account<'info, Mint>,

    pub authority: Signer<'info>,
    pub config: Account<'info, Config>,
    pub registry: Account<'info, qiara::Registry>,
    pub epoch_config: Account<'info, qiara::EpochConfig>,

    #[account(mut)]
    pub fee_recipient_ata: Option<Account<'info, TokenAccount>>,

    #[account(seeds = [b"exempt", from.owner.as_ref()], bump)]
    pub sender_exempt: Option<Account<'info, ExemptRecord>>,
    #[account(seeds = [b"exempt", to.owner.as_ref()], bump)]
    pub recipient_exempt: Option<Account<'info, ExemptRecord>>,

    pub token_program: Program<'info, Token>,
}

#[derive(Accounts)]
pub struct SetFeeExempt<'info> {
    #[account(mut)]
    pub signer: Signer<'info>,

    /// CHECK: Target wallet
    pub target_wallet: AccountInfo<'info>,

    #[account(
        init_if_needed,
        payer = signer,
        space = 8 + 32 + 1,
        seeds = [b"exempt", target_wallet.key().as_ref()],
        bump
    )]
    pub exempt_record: Account<'info, ExemptRecord>,

    pub config: Account<'info, Config>,
    pub registry: Account<'info, qiara::Registry>,
    pub system_program: Program<'info, System>,
}

// =========================================================================
// EVENTS & ERRORS
// =========================================================================

#[event]
pub struct ZkMintEvent {
    pub recipient: Pubkey,
    pub amount: u64,
    pub nullifier: [u8; 32],
}

#[error_code]
pub enum QiaraTokenError {
    #[msg("Input length must equal 128 bytes for 4 public signals.")]
    InvalidInputLength,
    #[msg("Alt-BN128 Groth16 proof verification failed.")]
    InvalidProof,
    #[msg("Validator signatures below required quorum.")]
    InsufficientSignatures,
    #[msg("Recipient does not match ZK public input address.")]
    UnauthorizedRecipient,
    #[msg("Transfer fee exceeds total transfer amount.")]
    FeeExceedsAmount,
    #[msg("Signer is not authorized to edit whitelist.")]
    UnauthorizedWhitelistAdmin,
}