use anchor_lang::prelude::*;
use events; // Imports the shared dynamic events library

// This is your on-chain program ID. 
// When you deploy, replace this with the ID generated by `anchor keys list`.
declare_id!("H6iGwFKdoSmG5wmi6RYGDYtQQo2ouDRYTLycx1psrTs7");

#[program]
pub mod shared {
    use super::*;

    /// Permissionless instruction to log dynamic storage creation parameters
    pub fn m_create_shared_storage(
        ctx: Context<StatelessEvent>,
        name: String,
        ref_code: String,
        used_ref_code: String,
        selected_validator: String,
        xp_tax: u64,
        fee_tax: u64,
    ) -> Result<()> {
        // Assert validations (matching Sui aborts)
        require!(!name.is_empty(), QiaraError::SharedNameCantBeEmpty);
        require!(!ref_code.is_empty(), QiaraError::RefCodeCantBeEmpty);

        let sender = ctx.accounts.sender.key();

        // Pack values into the generic dynamic vector structure
        let data = vec![
            events::create_data_struct("sender".to_string(), "address".to_string(), sender.to_bytes().to_vec()),
            events::create_data_struct("name".to_string(), "string".to_string(), name.as_bytes().to_vec()),
            events::create_data_struct("ref_code".to_string(), "string".to_string(), ref_code.as_bytes().to_vec()),
            events::create_data_struct("used_ref_code".to_string(), "string".to_string(), used_ref_code.as_bytes().to_vec()),
            events::create_data_struct("selected_validator".to_string(), "string".to_string(), selected_validator.as_bytes().to_vec()),
            events::create_data_struct("xp_tax".to_string(), "u64".to_string(), xp_tax.to_le_bytes().to_vec()),
            events::create_data_struct("fee_tax".to_string(), "u64".to_string(), fee_tax.to_le_bytes().to_vec()),
        ];

        // Emit the event via the shared library
        events::emit_event("Modular Storage Creation".to_string(), data)?;
        Ok(())
    }

    /// Logs permissioned add sub-owner actions
    pub fn p_allow_sub_owner(
        ctx: Context<StatelessEvent>,
        name: String,
        sub_owner: Vec<u8>,
    ) -> Result<()> {
        safety_check(&name, &sub_owner)?;

        let sender = ctx.accounts.sender.key();
        let data = vec![
            events::create_data_struct("sender".to_string(), "address".to_string(), sender.to_bytes().to_vec()),
            events::create_data_struct("sub_owner".to_string(), "vector<u8>".to_string(), sub_owner),
            events::create_data_struct("name".to_string(), "string".to_string(), name.as_bytes().to_vec()),
        ];

        events::emit_event("Modular Storage Sub Owner Added".to_string(), data)?;
        Ok(())
    }

    /// Logs permissioned remove sub-owner actions
    pub fn p_remove_sub_owner(
        ctx: Context<StatelessEvent>,
        name: String,
        sub_owner: Vec<u8>,
    ) -> Result<()> {
        safety_check(&name, &sub_owner)?;

        let sender = ctx.accounts.sender.key();
        let data = vec![
            events::create_data_struct("sender".to_string(), "address".to_string(), sender.to_bytes().to_vec()),
            events::create_data_struct("sub_owner".to_string(), "vector<u8>".to_string(), sub_owner),
            events::create_data_struct("name".to_string(), "string".to_string(), name.as_bytes().to_vec()),
        ];

        events::emit_event("Modular Storage Sub Owner Removed".to_string(), data)?;
        Ok(())
    }

    /// Logs permissioned referral code modifications
    pub fn p_change_used_ref_code(
        ctx: Context<StatelessEvent>,
        name: String,
        sub_owner: Vec<u8>,
        new_used_ref_code: String,
    ) -> Result<()> {
        safety_check(&name, &sub_owner)?;

        let sender = ctx.accounts.sender.key();
        let data = vec![
            events::create_data_struct("sender".to_string(), "address".to_string(), sender.to_bytes().to_vec()),
            events::create_data_struct("sub_owner".to_string(), "vector<u8>".to_string(), sub_owner),
            events::create_data_struct("name".to_string(), "string".to_string(), name.as_bytes().to_vec()),
            events::create_data_struct("new_used_ref_code".to_string(), "string".to_string(), new_used_ref_code.as_bytes().to_vec()),
        ];

        events::emit_event("Modular Storage Used Ref Code Updated".to_string(), data)?;
        Ok(())
    }
}

// --- Accounts Contexts ---

/// All instructions in this interface perform state-validation and emit events,
/// but do not record data in program accounts. 
/// We only require the signer to authorize and pay for transaction execution.
#[derive(Accounts)]
pub struct StatelessEvent<'info> {
    #[account(mut)]
    pub sender: Signer<'info>,
}

// --- Helper Functions ---

/// Implements your original Move safety checks
fn safety_check(name: &str, sub_owner: &[u8]) -> Result<()> {
    require!(!name.is_empty(), QiaraError::SharedNameCantBeEmpty);
    require!(!sub_owner.is_empty(), QiaraError::SubOwnerCantBeEmpty);
    Ok(())
}

// --- Custom Errors (Mapped from Sui abort constants) ---

#[error_code]
pub enum QiaraError {
    #[msg("Shared name can't be empty")]
    SharedNameCantBeEmpty,       // Mapped from Sui constant: 0
    #[msg("Referral code can't be empty")]
    RefCodeCantBeEmpty,          // Mapped from Sui constant: 1
    #[msg("Sub owner can't be empty")]
    SubOwnerCantBeEmpty,         // Mapped from Sui constant: 2
}