    [package]
    name = "QiaraEventV1"
    version = "1.0.0"
    authors = []

    [addresses]
    event = "0xe97f40d139c4e86c610236ab5eb8801222755c13b70d78c74ec91d89b3b80023"
    std = "0x1"
    aptos_std = "0x1"
    Extensions = "0x1"
    [dev-addresses]


    [dependencies.AptosStdlib]
    git = "https://github.com/aptos-labs/aptos-core.git"
    rev = "testnet"
    subdir = "aptos-move/framework/aptos-stdlib"

    [dependencies.AptosFramework]
    git = "https://github.com/aptos-labs/aptos-core.git"
    rev = "testnet"
    subdir = "aptos-move/framework/aptos-framework"

    [dev-dependencies]